// Typed access to the self-hosted photo set. The manifest is generated by
// `scripts/fetch-images.mjs` (intrinsic dimensions + alt + blur placeholder),
// so width/height are always known — `next/image` can size without layout shift.
import manifest from "../public/images/manifest.json";

export interface ImageMeta {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
}

export const IMAGES = manifest as Record<string, ImageMeta>;
export type ImageName = keyof typeof manifest;

export function img(name: ImageName): ImageMeta {
  const m = IMAGES[name as string];
  if (!m) throw new Error(`Unknown image "${String(name)}" — run scripts/fetch-images.mjs`);
  return m;
}
